name       : python-pyinsane2
version    : 2.0.13
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/p/pyinsane2/pyinsane2-2.0.13.tar.gz : 0d519531d552e4512776225eb400a6a4a9bfc83a08918ec7fea19cb2fa7ec4ee
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python library to access and use image scanners (Linux/Sane/Windows/WIA/etc)
description: |
    Python library to access and use image scanners (Linux/Sane/Windows/WIA/etc)
builddeps  :
    - python-nose
rundeps    :
    - python-pillow
    - python-sane
build      : |
    %python3_setup
install    : |
    %python3_install
