name       : python-pyinsane2
version    : 2.0.9
release    : 2
source     :
    - https://github.com/jflesch/pyinsane/archive/2.0.9.tar.gz : ffb90c9bbad17182c9f0cb354dd7a898aba5f821628462f9e7a92837f837fd85
license    : GPL-3.0
component  : programming.python
summary    : Python library to access and use image scanners (Linux/Sane/Windows/WIA/etc)
description: |
    Python library to access and use image scanners (Linux/Sane/Windows/WIA/etc)
builddeps  :
    - python-nose
    - python-setuptools
rundeps    :
    - python-sane
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
